/*
 * loader.js -- the loader movie's ActionScript, translated.
 *
 * GENERATED by tools/transpile.py from FFDec's deobfuscated export of the original SWF.
 * Do not edit by hand: change the translator, or add an entry to its fixes, and rerun.
 *
 * Each function is one script from the original, keyed by where it ran.  The comment
 * above each gives the path FFDec exported it under, so any line here can be checked
 * against the decompiled source.
 */
(function (registry) {

   /* DefineButton2_124/BUTTONCONDACTION on(release, keyPress Space).as */
   registry["b124:0"] = function (__scope)
   {
      with (__scope)
      {
      _parent?.gotoAndStop?.("allstop");
      }
   };

   /* DefineButton2_141/BUTTONCONDACTION on(release, keyPress Space).as */
   registry["b141:0"] = function (__scope)
   {
      with (__scope)
      {
      _parent?.gotoAndStop?.("loading");
      }
   };

   /* frame_1/DoAction.as */
   registry["root:1:1"] = function (__scope)
   {
      with (__scope)
      {
      fscommand?.("allowscale", false);
      fscommand?.("showmenu", false);
      _quality = "medium";
      SCREENX = 600;
      SCREENY = 400;
      SCREENX2 = 300;
      SCREENY2 = 200;
      play?.();
      }
   };

   /* frame_1/DoAction_2.as */
   registry["root:1:2"] = function (__scope)
   {
      with (__scope)
      {
      LoaderGame = function LoaderGame(MC)
      {
         this.MC = MC?.createEmptyMovieClip?.("game", 1);
         this.sfx = new LoaderSFX(this);
         this.cursor = new LoaderCursor(this);
         this.pigeons = new Array();
         this.maxPigeons = 25;
         this.pigeonCounter = 0;
         this.engaged = false;
         this.init = function ()
         {
            var _loc2_ = 0;
            while(_loc2_ < 10)
            {
               this.spawnPigeon?.();
               _loc2_ = _loc2_ + 1;
            }
         };
         this.handle = function ()
         {
            this.sfx?.handle?.();
            __as.set(this.cursor, "spinning", false);
            this.target = false;
            var _loc3_ = 0;
            var _loc2_;
            var _loc4_;
            while(_loc3_ < this.pigeons?.length)
            {
               _loc2_ = this.pigeons?.[_loc3_];
               if(!_loc2_?.active)
               {
                  this.pigeons?.splice?.(_loc3_, 1);
               }
               else
               {
                  _loc2_?.handle?.();
                  _loc4_ = this.cursor?.overTarget?.(_loc2_);
                  __as.set(this.cursor, "spinning", this.cursor?.spinning || _loc4_);
                  if(_loc4_)
                  {
                     this.target = _loc2_;
                  }
               }
               _loc3_ = _loc3_ + 1;
            }
            this.cursor?.handle?.();
         };
         this.spawnPigeon = function ()
         {
            var _loc2_ = this.pigeons?.length + 1;
            if(_loc2_ > this.maxPigeons)
            {
               return undefined;
            }
            var _loc3_ = this.pigeons?.push?.(new LoaderPigeon(this, 100 + this.pigeonCounter++));
         };
         this.destroy = function ()
         {
            Mouse.show();
            this.flash?.();
            this.MC?.removeMovieClip?.();
         };
         this.flash = function ()
         {
            _root?.flasher?.gotoAndPlay?.("shot");
         };
         this.init?.();
      };
      }
   };

   /* frame_1/DoAction_3.as */
   registry["root:1:3"] = function (__scope)
   {
      with (__scope)
      {
      LoaderCursor = function LoaderCursor(parent)
      {
         this.parent = parent;
         this.MC = this.parent?.MC?.attachMovie?.("cursor", "cursor", 10000);
         // (Smooth drawing: the pointer is drawn where the mouse is at the moment of drawing.)
         if(this.MC)
         {
            this.MC.$pointer = true;
         }
         this.MCdraw = this.parent?.MC?.createEmptyMovieClip?.("draw", 9999);
         this.filterGlow = new flash.filters.GlowFilter(16777215, 100, 12, 12, 2, 1, false, false);
         __as.set(MCdraw, "filters", new Array(this.filterGlow));
         this.MC?.gotoAndStop?.(1);
         this.fireRecharge = 10;
         this.fireCharge = 0;
         this.posX = 0;
         this.posY = 0;
         this.spinning = false;
         this.gunPost = 0;
         this.handle = function ()
         {
            this.posX = _xmouse;
            this.posY = _ymouse;
            __as.set(this.MC, "_x", this.posX);
            __as.set(this.MC, "_y", this.posY);
            if(this.spinning)
            {
               this.MC?.play?.();
            }
            else
            {
               if(this.MC?._currentframe == 1)
               {
                  this.MC?.stop?.();
               }
            }
            __as.set(this.MCdraw, "_alpha", 100 * this.fireCharge / this.fireRecharge);
            if(_ymouse > 345 && _xmouse > 100 && _xmouse < SCREENX - 100)
            {
               Mouse.show();
               return undefined;
            }
            Mouse.hide();
            if(this.fireCharge)
            {
               this.fireCharge--;
            }
            else
            {
               if(MOUSEDOWN)
               {
                  this.shoot?.();
               }
            }
            if(!MOUSEDOWN)
            {
               this.fireCharge = 0;
            }
         };
         this.shoot = function ()
         {
            __as.set(this.parent, "engaged", true);
            if(this.gunPost > 3)
            {
               this.gunPost = 0;
            }
            this.spinning = true;
            this.gunPost++;
            this.fireCharge = this.fireRecharge;
            this.parent?.flash?.();
            this.parent?.sfx?.play?.("fire" + (random?.(2) + 1));
            var _loc2_ = this.MCdraw;
            _loc2_?.clear?.();
            _loc2_?.lineStyle?.(3, 16777215, 100);
            if(this.gunPost == 1)
            {
               _loc2_?.moveTo?.(0, 0);
            }
            if(this.gunPost == 2)
            {
               _loc2_?.moveTo?.(SCREENX, 0);
            }
            if(this.gunPost == 3)
            {
               _loc2_?.moveTo?.(SCREENX, SCREENY);
            }
            if(this.gunPost == 4)
            {
               _loc2_?.moveTo?.(0, SCREENY);
            }
            _loc2_?.lineTo?.(this.posX, this.posY);
            this.parent?.target?.explode?.();
         };
         this.overTarget = function (target)
         {
            var _loc3_ = this.posX - target?.posX;
            var _loc2_ = this.posY - target?.posY;
            var _loc5_ = _loc3_ * _loc3_ + _loc2_ * _loc2_;
            return _loc5_ < target?.size * target?.size;
         };
      };
      }
   };

   /* frame_1/DoAction_4.as */
   registry["root:1:4"] = function (__scope)
   {
      with (__scope)
      {
      LoaderPigeon = function LoaderPigeon(parent, depth)
      {
         this.parent = parent;
         this.depth = depth;
         this.MC = this.parent?.MC?.attachMovie?.("pigeon", "pigeon" + this.depth, this.depth);
         __as.set(this.MC, "_rotation", random?.(40) - 20);
         this.angle = random?.(360);
         this.bulk = random?.(400) + 50;
         this.pace = random?.(200) + 50;
         this.count = 0;
         this.ax = Math.sin(this.angle / 6.283185307179586);
         this.ay = Math.cos(this.angle / 6.283185307179586);
         this.active = true;
         this.baseX = SCREENX2 + SCREENX / 500 * (random?.(100) - 50);
         this.baseY = SCREENY2 + SCREENY / 500 * (random?.(100) - 50);
         this.init = function ()
         {
            this.handle?.();
         };
         this.handle = function ()
         {
            this.count++;
            this.perc = this.count / this.pace;
            this.perc = this.perc * this.perc * this.perc;
            this.posX = this.baseX + hyp * this.ax * this.perc;
            this.posY = this.baseY + hyp * this.ay * this.perc;
            if(this.perc > 1)
            {
               this.parent?.spawnPigeon?.();
               this.destroy?.();
            }
            this.size = 0.3 * this.perc * this.bulk;
            this.draw?.();
         };
         this.draw = function ()
         {
            __as.set(this.MC, "_x", this.posX);
            __as.set(this.MC, "_y", this.posY);
            __as.set(this.MC, "_xscale", this.perc * this.bulk);
            __as.set(this.MC, "_yscale", this.perc * this.bulk);
            __as.set(this.MC, "_alpha", 50 + this.perc * 2 * 100);
            this.depth = Math.round(this.perc * 1000) + 100;
            this.MC?.swapDepths?.(this.depth);
         };
         this.explode = function ()
         {
            this.parent?.MC?.attachMovie?.("explosion", "explosion" + this.depth, this.depth, {_x:this.MC?._x,_y:this.MC?._y,_xscale:this.MC?._xscale,_yscale:this.MC?._yscale,_rotation:this.MC?._rotation});
            this.parent?.sfx?.play?.("explosion" + (random?.(2) + 1));
            this.parent?.spawnPigeon?.();
            this.parent?.spawnPigeon?.();
            this.destroy?.();
         };
         this.destroy = function ()
         {
            this.active = false;
            this.MC?.removeMovieClip?.();
         };
         this.init?.();
      };
      hyp = Math.sqrt(SCREENX2 * SCREENX2 + SCREENY2 * SCREENY2) * 1.5;
      }
   };

   /* frame_1/DoAction_5.as */
   registry["root:1:5"] = function (__scope)
   {
      with (__scope)
      {
      LoaderSFX = function LoaderSFX(parent)
      {
         this.parent = parent;
         this.MC = this.parent?.MC?.attachMovie?.("soundFX", "soundFX", 3);
         this.sound = new Sound(this.MC);
         this.buffer = new Array();
         this.handle = function ()
         {
            var _loc2_ = this.buffer?.shift?.();
            if(_loc2_?.length)
            {
               this.fire?.(_loc2_);
            }
         };
         this.play = function (what)
         {
            if(this.buffer?.length < 10 || what?.substr?.(0, 5) == "music")
            {
               this.buffer?.push?.(String?.(what));
            }
         };
         this.fire = function (what)
         {
            this.MC?.gotoAndPlay?.(what);
         };
         this.mute = function (onOrOff)
         {
            this.sound?.setVolume?.(Number?.(!onOrOff) * 100);
         };
      };
      }
   };

   /* frame_10/DoAction.as */
   registry["root:10:1"] = function (__scope)
   {
      with (__scope)
      {
      stop?.();
      reallyAloader = true;
      version = getVersion?.()?.split?.(" ")?.[1]?.split?.(",")?.[0];
      onEnterFrame = function ()
      {
         var _loc1_ = _level0?.getBytesLoaded?.() / _level0?.getBytesTotal?.() * 100;
         if(_loc1_ < 100)
         {
            return undefined;
         }
         if(version != parseFloat?.(version) || version < 8)
         {
            gotoAndStop?.("version");
         }
         else
         {
            if(_level0?.asseturl?.length > 0 || _level0?.http_host?.length > 0)
            {
               gotoAndStop?.("loading");
            }
            else
            {
               __as.set(_level0, "asseturl", "");
               gotoAndStop?.("button");
            }
         }
      };
      }
   };

   /* frame_20/DoAction.as */
   registry["root:20:1"] = function (__scope)
   {
      with (__scope)
      {
      System.security?.allowDomain?.("*");
      fileName = _level0?.asseturl + "game.swf";
      if(reallyAloader)
      {
         loadMovieNum?.(fileName, 1);
      }
      percent = 0;
      frame = 1;
      k = 0;
      this.game = new LoaderGame(_root?.bg?.blank);
      stop?.();
      onMouseDown = function ()
      {
         MOUSEDOWN = true;
      };
      onMouseUp = function ()
      {
         MOUSEDOWN = false;
      };
      onEnterFrame = function ()
      {
         this.game?.handle?.();
         if(!reallyAloader)
         {
            k += 1;
            if(k > 100)
            {
               k = 100;
            }
         }
         if(percent < 100)
         {
            _level1?.stop?.();
            __as.set(_level1, "_visible", false);
            percent = _level1?.getBytesLoaded?.() / _level1?.getBytesTotal?.() * 100;
            if(_level1?.getBytesLoaded?.() == undefined)
            {
               percent = 0;
            }
            if(!reallyAloader)
            {
               percent = k;
            }
            frame = Math.ceil(percent);
            if(frame < 1)
            {
               frame = 1;
            }
            if(frame > 100)
            {
               frame = 100;
            }
            loader_bar?.gotoAndStop?.(frame);
            __as.set(loader_bar, "message", 42000000 - Math.round(percent * 420000) + " KM");
         }
         else
         {
            _level1?.stop?.();
            if(this.game?.engaged)
            {
               _level0?.gotoAndStop?.("loaded");
            }
            else
            {
               _level0?.gotoAndStop?.("allstop");
            }
         }
      };
      }
   };

   /* frame_25/DoAction.as */
   registry["root:25:1"] = function (__scope)
   {
      with (__scope)
      {
      stop?.();
      }
   };

   /* frame_30/DoAction.as */
   registry["root:30:1"] = function (__scope)
   {
      with (__scope)
      {
      stop?.();
      }
   };

   /* frame_35/DoAction.as */
   registry["root:35:1"] = function (__scope)
   {
      with (__scope)
      {
      onMouseDown = function ()
      {
      };
      onMouseUp = function ()
      {
      };
      onEnterFrame = function ()
      {
      };
      this.game?.destroy?.();
      delete this.game;
      _level1?.play?.();
      __as.set(_level1, "_visible", true);
      stop?.();
      }
   };

   /* DefineSprite_4_streak5/frame_101/DoAction.as */
   registry["s4:101:1"] = function (__scope)
   {
      with (__scope)
      {
      this.removeMovieClip?.();
      }
   };

   /* DefineSprite_5_streak4/frame_101/DoAction.as */
   registry["s5:101:1"] = function (__scope)
   {
      with (__scope)
      {
      this.removeMovieClip?.();
      }
   };

   /* DefineSprite_6_streak3/frame_101/DoAction.as */
   registry["s6:101:1"] = function (__scope)
   {
      with (__scope)
      {
      this.removeMovieClip?.();
      }
   };

   /* DefineSprite_7_streak2/frame_101/DoAction.as */
   registry["s7:101:1"] = function (__scope)
   {
      with (__scope)
      {
      this.removeMovieClip?.();
      }
   };

   /* DefineSprite_8_streak1/frame_101/DoAction.as */
   registry["s8:101:1"] = function (__scope)
   {
      with (__scope)
      {
      this.removeMovieClip?.();
      }
   };

   /* DefineSprite_52_explosion/frame_11/DoAction.as */
   registry["s52:11:1"] = function (__scope)
   {
      with (__scope)
      {
      this.removeMovieClip?.();
      }
   };

   /* DefineSprite_106_soundFX/frame_1/DoAction.as */
   registry["s106:1:1"] = function (__scope)
   {
      with (__scope)
      {
      stop?.();
      }
   };

   /* DefineSprite_106_soundFX/frame_10/DoAction.as */
   registry["s106:10:1"] = function (__scope)
   {
      with (__scope)
      {
      play?.();
      }
   };

   /* DefineSprite_106_soundFX/frame_19/DoAction.as */
   registry["s106:19:1"] = function (__scope)
   {
      with (__scope)
      {
      gotoAndStop?.(1);
      }
   };

   /* DefineSprite_106_soundFX/frame_20/DoAction.as */
   registry["s106:20:1"] = function (__scope)
   {
      with (__scope)
      {
      play?.();
      }
   };

   /* DefineSprite_106_soundFX/frame_29/DoAction.as */
   registry["s106:29:1"] = function (__scope)
   {
      with (__scope)
      {
      gotoAndStop?.(1);
      }
   };

   /* DefineSprite_106_soundFX/frame_30/DoAction.as */
   registry["s106:30:1"] = function (__scope)
   {
      with (__scope)
      {
      play?.();
      }
   };

   /* DefineSprite_106_soundFX/frame_39/DoAction.as */
   registry["s106:39:1"] = function (__scope)
   {
      with (__scope)
      {
      gotoAndStop?.(1);
      }
   };

   /* DefineSprite_106_soundFX/frame_40/DoAction.as */
   registry["s106:40:1"] = function (__scope)
   {
      with (__scope)
      {
      play?.();
      }
   };

   /* DefineSprite_106_soundFX/frame_49/DoAction.as */
   registry["s106:49:1"] = function (__scope)
   {
      with (__scope)
      {
      gotoAndStop?.(1);
      }
   };

   /* DefineSprite_106_soundFX/frame_50/DoAction.as */
   registry["s106:50:1"] = function (__scope)
   {
      with (__scope)
      {
      play?.();
      }
   };

   /* DefineSprite_106_soundFX/frame_59/DoAction.as */
   registry["s106:59:1"] = function (__scope)
   {
      with (__scope)
      {
      gotoAndStop?.(1);
      }
   };

   /* DefineSprite_127/frame_1/DoAction.as */
   registry["s127:1:1"] = function (__scope)
   {
      with (__scope)
      {

      }
   };

   /* DefineSprite_136/frame_1/DoAction.as */
   registry["s136:1:1"] = function (__scope)
   {
      with (__scope)
      {
      spawnStar = function spawnStar(pos)
      {
         i++;
         if(i > 300)
         {
            i = 1;
         }
         var _loc2_ = this.attachMovie?.("streak" + (random?.(5) + 1), "star" + i, i);
         __as.set(_loc2_, "_rotation", random?.(360));
         if(pos)
         {
            _loc2_?.gotoAndPlay?.(random?.(100));
            __as.set(_loc2_, "_alpha", 1000);
         }
      };
      i = 0;
      count = 0;
      k = 0;
      while(k < 100)
      {
         spawnStar?.(true);
         k++;
      }
      onEnterFrame = function ()
      {
         count++;
         var _loc3_ = 2;
         if(count < 200)
         {
            _loc3_ = count / 100;
         }
         var _loc2_ = 0;
         while(_loc2_ < 3)
         {
            spawnStar?.();
            _loc2_ = _loc2_ + 1;
         }
         this._rotation += Math.cos(count / 100) * _loc3_;
      };
      }
   };

   /* DefineSprite_140/frame_11/DoAction.as */
   registry["s140:11:1"] = function (__scope)
   {
      with (__scope)
      {
      stop?.();
      }
   };

   /* DefineSprite_140/frame_20/DoAction.as */
   registry["s140:20:1"] = function (__scope)
   {
      with (__scope)
      {
      stop?.();
      }
   };

   /* DefineSprite_143/frame_1/DoAction.as */
   registry["s143:1:1"] = function (__scope)
   {
      with (__scope)
      {

      }
   };

})((globalThis.__scripts = globalThis.__scripts || {})["loader"] = {});
